# Generated by Django 5.0 on 2025-09-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='education',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='headline',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='work_experience',
            field=models.TextField(default=''),
        ),
    ]
