# Generated by Django 5.0 on 2025-09-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_jobseekerprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
