# Generated by Django 5.0 on 2025-09-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('seeker', 'Seeker')], default=None, max_length=10),
        ),
    ]
