# Generated by Django 5.0 on 2025-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_active_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_recruiter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seeker',
        ),
        migrations.AlterField(
            model_name='user',
            name='active_role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('seeker', 'Seeker')], default='seeker', max_length=10),
        ),
    ]
