# Generated by Django 5.0 on 2025-09-26 00:21

import django.db.models.deletion
import seeker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('projects', models.TextField()),
                ('work_experience', models.TextField()),
                ('skills', models.TextField()),
                ('privacy', models.JSONField(default=seeker.models.get_default_privacy)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='seeker.jobseekerprofile')),
            ],
        ),
    ]
