# Generated by Django 5.0 on 2025-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='projects',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
