# Generated by Django 5.0 on 2025-09-23 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_jobseekerprofile_location_jobseekerprofile_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='links',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='seeker.jobseekerprofile')),
            ],
        ),
    ]
