# Generated by Django 5.0 on 2025-09-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0003_remove_jobseekerprofile_links_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='privacy',
            field=models.JSONField(default={'education': 'public', 'headline': 'public', 'location': 'public', 'projects': 'public', 'skills': 'public', 'work_experience': 'public'}),
        ),
    ]
