# Generated by Django 5.0 on 2025-09-23 05:47

import seeker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_jobseekerprofile_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='privacy',
            field=models.JSONField(default=seeker.models.get_default_privacy),
        ),
    ]
