# Generated by Django 5.0 on 2025-10-02 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seeker', '0002_alter_jobseekerprofile_education_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=200)),
                ('search_criteria', models.JSONField(default=dict, help_text='Saved search parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to send notifications for new matches')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('recruiter', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.jobseekerprofile')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='recruiter.savedsearch')),
            ],
            options={
                'unique_together': {('saved_search', 'candidate_profile')},
            },
        ),
    ]
