# Generated by Django 5.0 on 2025-10-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together={('recruiter', 'name')},
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_notified',
            field=models.DateTimeField(blank=True, help_text='Last time recruiter was notified about new matches', null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='location_query',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='projects_query',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='skills_query',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(help_text='Name for this saved search', max_length=255),
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='search_criteria',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='updated_at',
        ),
    ]
