<<<<<<< HEAD
# Generated by Django 5.0 on 2025-10-23 07:31

from django.db import migrations
=======
# Generated by Django 5.0 on 2025-10-23 02:53

from django.db import migrations, connection


def check_and_delete_searchnotification(apps, schema_editor):
    """Check if SearchNotification table exists before deleting it"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='recruiter_searchnotification'
        """)
        if cursor.fetchone():
            # Table exists, delete it
            cursor.execute("DROP TABLE recruiter_searchnotification")


def reverse_check_and_delete_searchnotification(apps, schema_editor):
    """Reverse operation - recreate SearchNotification table if needed"""
    # This is a no-op since we're removing the model entirely
    pass
>>>>>>> origin/main


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_savedsearch_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together=set(),
        ),
<<<<<<< HEAD
        migrations.DeleteModel(
            name='SearchNotification',
=======
        migrations.RunPython(
            check_and_delete_searchnotification,
            reverse_check_and_delete_searchnotification,
>>>>>>> origin/main
        ),
    ]
