# Generated by Django 5.0 on 2025-10-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_savedsearch_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='SearchNotification',
        ),
    ]
