# Generated by Django 5.0 on 2025-10-24 02:28

from django.db import migrations, connection


def ensure_searchnotification_deleted(apps, schema_editor):
    """Ensure SearchNotification table is deleted if it exists"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='recruiter_searchnotification'
        """)
        if cursor.fetchone():
            # Table exists, delete it
            cursor.execute("DROP TABLE recruiter_searchnotification")


def reverse_ensure_searchnotification_deleted(apps, schema_editor):
    """Reverse operation - this is a no-op since we're removing the model entirely"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_savedsearch_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(
            ensure_searchnotification_deleted,
            reverse_ensure_searchnotification_deleted,
        ),
    ]
