# Generated by Django 5.0 on 2025-10-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_auto_20251023_2228'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='SearchNotification',
                ),
            ],
            database_operations=[
                # No database operations needed since table doesn't exist
            ],
        ),
    ]
