# Generated by Django 5.0 on 2025-10-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Phone Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20),
        ),
    ]
